### ISSUE TITLE
const used in strict mode

### ISSUE THREAD

**Issue by idahotallpaul** [khalwat/generator-nystudio107#1]
Hi. Installed via `sudo npm -g install generator-nystudio107`. When I run `yo nystudio107` is breaks.

```
/usr/local/lib/node_modules/generator-nystudio107/app/index.js:35
const QUESTIONS = [
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object._storeAsPath.Object.defineProperty.get [as nystudio107:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:243:16)
    at Environment.create (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:261:24)
```

Do I need to do something to be able to run this?

Thanks.

**Comment by khalwat** [comment]
That's because you're running an old version of NodeJS.  You can do one of two things:

1) Upgrade to the latest NodeJS (recommended)

-OR-

2) Remove the `uses strict;` from the `index.js` file
